"""multi-tenancy: agregar organizations y organization_id

Revision ID: a8033b0a931c
Revises: d013153e75b3
Create Date: 2026-07-08 20:51:25.715058

"""
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8033b0a931c'
down_revision: Union[str, None] = 'd013153e75b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    # PASO 1: agregar las columnas como NULLABLE primero. Si se agregaran
    # directamente como NOT NULL, esta migración fallaría en cualquier
    # base con datos existentes (como pasó al probarla aquí: había 3
    # usuarios y 1 aula ya creados antes de introducir multi-tenancy).
    op.add_column('classrooms', sa.Column('organization_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('organization_id', sa.String(), nullable=True))

    # PASO 2: backfill — todo lo que ya existía se asigna a una
    # organización "Legacy" explícita, para que quede auditable qué datos
    # son de antes del multi-tenancy en vez de asignarlos silenciosamente
    # a la primera organización real que se cree después.
    conn = op.get_bind()
    legacy_org_id = uuid.uuid4().hex
    conn.execute(
        sa.text("INSERT INTO organizations (id, name, created_at) VALUES (:id, :name, now())"),
        {"id": legacy_org_id, "name": "Legacy (pre multi-tenancy)"},
    )
    conn.execute(
        sa.text("UPDATE users SET organization_id = :org_id WHERE organization_id IS NULL"),
        {"org_id": legacy_org_id},
    )
    conn.execute(
        sa.text("UPDATE classrooms SET organization_id = :org_id WHERE organization_id IS NULL"),
        {"org_id": legacy_org_id},
    )

    # PASO 3: recién ahora es seguro exigir NOT NULL + la foreign key.
    op.alter_column('users', 'organization_id', nullable=False)
    op.alter_column('classrooms', 'organization_id', nullable=False)
    op.create_foreign_key(None, 'classrooms', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'classrooms', type_='foreignkey')
    op.drop_column('classrooms', 'organization_id')
    op.drop_table('organizations')
    # ### end Alembic commands ###
