"""compliance de datos de menores: consentimiento y auditoria

Revision ID: cc1706fd3ce3
Revises: e05f2778ce39
Create Date: 2026-07-10 02:02:28.117836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc1706fd3ce3'
down_revision: Union[str, None] = 'e05f2778ce39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('consent_type', sa.Enum('data_processing', 'media_recording', 'marketing', name='consenttype'), nullable=False),
    sa.Column('guardian_full_name', sa.String(), nullable=False),
    sa.Column('guardian_email', sa.String(), nullable=False),
    sa.Column('granted_by_user_id', sa.String(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_access_audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=False),
    sa.Column('subject_student_id', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('view_profile', 'export_data', 'erase_data', name='dataaccessaction'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('guardian_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'guardian_email')
    op.drop_column('users', 'date_of_birth')
    op.drop_table('data_access_audit_log')
    op.drop_table('consent_records')
    # ### end Alembic commands ###
